// <auto-generated />
namespace WebZapService.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class col_country_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(col_country_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201502111103376_col_country_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
